/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.charset.StandardCharsets;

import java.util.LinkedList;
import java.util.Scanner;
import java.net.*;
import java.io.*;

public class App {
	private static MyEngine myEngine;
	private static EnemyEngine enemyEngine;

	private static ServerSocket server = null;
	private static Socket client = null;

	private static Scanner user = null;
	private static DataInputStream in = null;
	private static DataOutputStream out = null;

	private static int HISTORY = 15;
	private static LinkedList<String> history;
	private static int historyStart;

	private static void startServer(int port) throws Exception {
		System.out.println("Starting server on port " + port);

		server = new ServerSocket(port);
		System.out.println("Started server on port " + port);

		System.out.println("Waiting for client...");
		client = server.accept();
		System.out.println("Client accepted.");

		in = new DataInputStream(
                new BufferedInputStream(client.getInputStream()));
		out = new DataOutputStream(
				new BufferedOutputStream(client.getOutputStream()));

		System.out.println("Ready to start the game\n");
	}

	private static void startClient(String hostname, int port) throws Exception {
		System.out.println("Connecting to " + hostname + ":" + port);

		client = new Socket(hostname, port);
		System.out.println("Connected to server.");

		in = new DataInputStream(
                new BufferedInputStream(client.getInputStream()));
		out = new DataOutputStream(
				new BufferedOutputStream(client.getOutputStream()));


		System.out.println("Ready to start the game\n");
	}

	private static void addHistory(String msg) {
		history.add(msg);
		while (history.size() > HISTORY) {
			history.remove(0);
			historyStart++;
		}
	}

	private static void render() throws Exception {
		System.out.print("\033[H\033[2J");

		System.out.println("   ===YOUR===             ===ENEMY==");
		System.out.println("   12345678910            12345678910");
		System.out.println();
		for (int row = 0; row < 10; row++) {
			System.out.print("" + (char)(('A' + row)) + "  ");
			for (int i = 0; i < 10; i++) {
				System.out.print(myEngine.get(row, i));
			}

			System.out.print("           ");
			System.out.print("" + (char)(('A' + row)) + " ");

			for (int i = 0; i < 10; i++) {
				System.out.print(enemyEngine.get(row, i));
			}

			System.out.println();
		}

		System.out.println("\nHistory (oldest first):\n");
		for (int i = 0; i < HISTORY; i++) {
			if (history.size() <= i) {
				break;
			}
			System.out.print("" + (i + historyStart) + ". ");
			System.out.print(history.get(i));
		}
		System.out.println();

		System.out.flush();
	}

	private static int[] askMove() throws Exception {
		System.out.print(">>> Enter your move (Z to exit): ");

		int row = -1;
		int col = -1;

		while (row == -1) {
			try {
				String line = user.next();

				int r = line.charAt(0) - 'A';
				if (r == 'Z' - 'A') {
					System.out.println("Exiting, bye bye!");
					return null;
				}
				int c = Integer.parseInt(line.substring(1)) - 1;

				if (!(0 <= r && r < 10 && 0 <= c && c < 10)) {
					col = -1;
					row = -1;
					System.out.print("\n>>> Invalid cell, try again: ");
					continue;
				}

				row = r;
				col = c;
				break;
			}
			catch (Exception e) {
				System.out.print("\n>>> Invalid move, try again: ");
			}
		}

		return new int[]{row, col};
	}

	private static void gameloop(boolean movesFirst) throws Exception {
		render();

		int lastRow = -1, lastCol = -1;

		if (movesFirst) {
			int[] move = askMove();
			if (move == null) {
				return;
			}

			char row = (char)(move[0] + 'A');
			String col = "" + (move[1] + 1);

			lastRow = move[0];
			lastCol = move[1];

			addHistory("you: start;" + row + col + "\n");
			render();
			out.writeUTF("start;" + row + col + "\n");
			out.flush();
		}

		while (!client.isClosed()) {
			render();

			String msg = in.readUTF();
			addHistory("them: " + msg);
			render();

			String cmd = null;
			String coords = null;
			String res = "";

			if (msg.equals("ostatni zatopiony\n")) {
				enemyEngine.update(lastRow, lastCol, EnemyEngine.HitResult.Destroy);
				render();
				System.out.println("Wygrana");
				return;
			}

			try {
				String[] arr = msg.split(";");

				cmd = arr[0].trim();
				coords = arr[1].trim();

				int row = coords.charAt(0) - 'A';
				int col = Integer.parseInt(coords.substring(1)) - 1;

				if (!(0 <= row && row < 10 && 0 <= col && col < 10)) {
					render();
					System.out.println("Błąd komunikacji: " + msg);
					return;
				}

				if (cmd.equals("start")) {
				}
				else if (cmd.equals("pudło")) {
					enemyEngine.update(lastRow, lastCol, EnemyEngine.HitResult.Miss);
				}
				else if (cmd.equals("trafiony")) {
					enemyEngine.update(lastRow, lastCol, EnemyEngine.HitResult.Hit);
				}
				else if (cmd.equals("trafiony zatopiony")) {
					enemyEngine.update(lastRow, lastCol, EnemyEngine.HitResult.Destroy);
				}
				else {
					render();
					System.out.println("Błąd komunikacji: " + msg);
					return;
				}

				MyEngine.HitResult hit = myEngine.hit(row, col);
				if (hit == MyEngine.HitResult.Miss) {
					res += "pudło;";
				}
				else if (hit == MyEngine.HitResult.Hit) {
					res += "trafiony;";
				}
				else if (hit == MyEngine.HitResult.Destroy) {
					res += "trafiony zatopiony;";
				}
				else {
					res += "ostatni zatopiony\n";
				}
			}
			catch (Exception e) {
				render();
				e.printStackTrace();
				System.out.println("Błąd komunikacji: " + msg);
				return;
			}

			if (res.equals("ostatni zatopiony\n")) {
				addHistory("you: " + res);
				render();
				System.out.println("Przegrana");
				out.writeUTF(res);
				out.flush();
				return;
			}

			render();
			int[] move = askMove();
			if (move == null) {
				return;
			}

			char row = (char)(move[0] + 'A');
			String col = "" + (move[1] + 1);

			lastRow = move[0];
			lastCol = move[1];

			res += row + col + "\n";

			addHistory("you: " + res);
			render();
			out.writeUTF(res);
			out.flush();
		}
	}

	private static void startGame(boolean isHost, int port, String map, String hostname) throws Exception {
		myEngine = new MyEngine(map);
		enemyEngine = new EnemyEngine();
		history = new LinkedList<>();
		historyStart = 1;

		user = new Scanner(System.in);

		if (isHost) {
			startServer(port);
		}
		else {
			startClient(hostname, port);
		}

		gameloop(!isHost);

		if (server != null) {
			server.close();
		}
		if (client != null) {
			client.close();
		}
	}

    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
			System.err.println("Not enough args.\n");
			return;
		}

		if (args[0].equals("-gen")) {
			System.out.println(BattleshipGenerator.defaultInstance().generateMap());
			return;
		}

		boolean isHost = true;
		int port = 7777;
		String map = null;
		String hostname = null;

		for (int i = 0; i < args.length; i++) {
			if (args[i].equals("-mode")) {
				i++;
				if (args[i].equals("client")) {
					isHost = false;
				}
			}
			else if (args[i].equals("-port")) {
				i++;
				port = Integer.parseInt(args[i]);
			}
			else if (args[i].equals("-map")) {
				i++;
				map = new String(Files.readAllBytes(Paths.get(args[i])), StandardCharsets.UTF_8)
					.trim();
			}
			else if (args[i].equals("-host")) {
				i++;
				hostname = args[i];
			}
		}

		startGame(isHost, port, map, hostname);
	}
}
